POST http://localhost:3000/basic/insert HTTP/1.1
Content-Type: application/json

{
    "data": [
        {
            "optionId": 4444444445,
            "companyId": 4444444444 ,
            "audienceCount": 1500,
            "cost": 150
        }
    ]
}

### 

GET http://localhost:3000/basic/data?companyId=9999999992&audienceCount=1&page=1&pageSize=2 HTTP/1.1
Content-Type: application/json


### 

GET http://localhost:3000/basic/data?audienceCount=1500&page=-1 HTTP/1.1
Content-Type: application/json


###
GET http://localhost:3000/basic/dataLength?companyId='9999999992' HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/basic/result?optionIds=&budget=30 HTTP/1.1
Content-Type: application/json


###
GET http://localhost:3000/basic/validateResultData HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/basic/asyncdata HTTP/1.1
Content-Type: application/json
