POST http://localhost:3000/basic/insert HTTP/1.1
Content-Type: application/json

{
    "data": [
        {
            "optionId": 2222222222,
            "companyId": 2222222222 ,
            "audienceCount": 1500,
            "cost": 150
        }
    ]
}

### 

GET http://localhost:3000/basic/data?companyId='1111111111'&page=1&pageSize=1 HTTP/1.1
Content-Type: application/json


### 

GET http://localhost:3000/basic/data?audienceCount=1500&page=-1 HTTP/1.1
Content-Type: application/json